import os
import sys
import time
import shutil
import argparse

from datetime import datetime


def get_args():
    """ Get command line arguments. """
    parser = argparse.ArgumentParser(
        description='Remove directories where modified dates before desired date.'
    )
    parser.add_argument(
        '-c', '--cutoff-date',
        dest='cutoff',
        required=True,
        help='Desired cutoff date: [ YYYY-MM-DD ]'
    )
    return parser.parse_args()


if __name__ == '__main__':

    args = get_args()
    cutoff_date = datetime.strptime('{} 00:00:00.00000'.format(args.cutoff), '%Y-%m-%d %H:%M:%S.%f')

    temp_dirs = [
        '/data/shared/CDC_EDLB_RefID_v1/temp',
        '/data/shared/CDC_EDLB_Ecoli_v4/temp',
        '/data/shared/CDC_EDLB_campy_v5_2/temp',
        '/data/shared/CDC_EDLB_Salm_v3/temp',
        '/data/shared/CDC_EDLB_listeria/temp',
        '/data/shared/AK_salmonella/temp',
        '/data/shared/AL_campy/temp',
        '/data/shared/AL_escherichia/temp',
        '/data/shared/AL_listeria/temp',
        '/data/shared/AL_refid/temp',
        '/data/shared/AL_salmonella/temp',
        '/data/shared/AR_campy/temp',
        '/data/shared/AR_escherichia/temp',
        '/data/shared/AR_listeria/temp',
        '/data/shared/AR_refid/temp',
        '/data/shared/AR_salmonella/temp',
        '/data/shared/ARS4_campy/temp',
        '/data/shared/ARS4_escherichia/temp',
        '/data/shared/ARS4_listeria/temp',
        '/data/shared/ARS4_refid/temp',
        '/data/shared/ARS4_salmonella/temp',
        '/data/shared/AZ_campy/temp',
        '/data/shared/AZ_escherichia/temp',
        '/data/shared/AZ_listeria/temp',
        '/data/shared/AZ_refid/temp',
        '/data/shared/AZ_salmonella/temp',
        '/data/shared/CA_campy/temp',
        '/data/shared/CA_escherichia/temp',
        '/data/shared/CA_listeria/temp',
        '/data/shared/CA_refid/temp',
        '/data/shared/CA_salmonella/temp',
        '/data/shared/CAOC_campy/temp',
        '/data/shared/CAOC_escherichia/temp',
        '/data/shared/CAOC_listeria/temp',
        '/data/shared/CAOC_refid/temp',
        '/data/shared/CAOC_salmonella/temp',
        '/data/shared/CASC_campy/temp',
        '/data/shared/CASC_escherichia/temp',
        '/data/shared/CASC_listeria/temp',
        '/data/shared/CASC_refid/temp',
        '/data/shared/CASC_salmonella/temp',
        '/data/shared/CDC_campy/temp',
        '/data/shared/CDC_cbot/temp',
        '/data/shared/CDC_EDLB_campy/temp',
        '/data/shared/CDC_EDLB_campy_v5_2/temp',
        '/data/shared/CDC_EDLB_cbot/temp',
        '/data/shared/CDC_EDLB_Ecoli_v4/temp',
        '/data/shared/CDC_EDLB_escherichia/temp',
        '/data/shared/CDC_EDLB_listeria/temp',
        '/data/shared/CDC_EDLB_refid/temp',
        '/data/shared/CDC_EDLB_RefID_v1/temp',
        '/data/shared/CDC_EDLB_Salm_v3/temp',
        '/data/shared/CDC_EDLB_salmonella/temp',
        '/data/shared/CDC_escherichia/temp',
        '/data/shared/CDC_listeria/temp',
        '/data/shared/CDC_refid/temp',
        '/data/shared/CDC_refid1/temp',
        '/data/shared/CDC_salmonella/temp',
        '/data/shared/CO_campy/temp',
        '/data/shared/CO_cdc_campy_v5_2/temp',
        '/data/shared/CO_escherichia/temp',
        '/data/shared/CO_listeria/temp',
        '/data/shared/CO_lmo_v5/temp',
        '/data/shared/CO_refid/temp',
        '/data/shared/CO_salmonella/temp',
        '/data/shared/CT_campy/temp',
        '/data/shared/CT_escherichia/temp',
        '/data/shared/CT_listeria/temp',
        '/data/shared/CT_refid/temp',
        '/data/shared/CT_salmonella/temp',
        '/data/shared/DE_campy/temp',
        '/data/shared/DE_escherichia/temp',
        '/data/shared/DE_listeria/temp',
        '/data/shared/DE_refid/temp',
        '/data/shared/DE_salmonella/temp',
        '/data/shared/FCF_campy/temp',
        '/data/shared/FCF_escherichia/temp',
        '/data/shared/FCF_listeria/temp',
        '/data/shared/FCF_listeria1/temp',
        '/data/shared/FCF_refid/temp',
        '/data/shared/FL_campy/temp',
        '/data/shared/FL_escherichia/temp',
        '/data/shared/FL_listeria/temp',
        '/data/shared/FL_refid/temp',
        '/data/shared/FL_salmonella/temp',
        '/data/shared/GA_campy/temp',
        '/data/shared/GA_escherichia/temp',
        '/data/shared/GA_listeria/temp',
        '/data/shared/GA_refid/temp',
        '/data/shared/GA_salmonella/temp',
        '/data/shared/HI_campy/temp',
        '/data/shared/HI_escherichia/temp',
        '/data/shared/HI_listeria/temp',
        '/data/shared/HI_refid/temp',
        '/data/shared/HI_salmonella/temp',
        '/data/shared/ID_campy/temp',
        '/data/shared/ID_escherichia/temp',
        '/data/shared/ID_listeria/temp',
        '/data/shared/ID_refid/temp',
        '/data/shared/ID_salmonella/temp',
        '/data/shared/IL_campy/temp',
        '/data/shared/IL_escherichia/temp',
        '/data/shared/IL_listeria/temp',
        '/data/shared/IL_refid/temp',
        '/data/shared/IL_salmonella/temp',
        '/data/shared/IN_campy/temp',
        '/data/shared/IN_escherichia/temp',
        '/data/shared/IN_listeria/temp',
        '/data/shared/IN_refid/temp',
        '/data/shared/IN_salmonella/temp',
        '/data/shared/KS_campy/temp',
        '/data/shared/KS_escherichia/temp',
        '/data/shared/KS_listeria/temp',
        '/data/shared/KS_refid/temp',
        '/data/shared/KS_salmonella/temp',
        '/data/shared/KY_campy/temp',
        '/data/shared/KY_escherichia/temp',
        '/data/shared/KY_listeria/temp',
        '/data/shared/KY_refid/temp',
        '/data/shared/KY_salmonella/temp',
        '/data/shared/LA_campy/temp',
        '/data/shared/LA_escherichia/temp',
        '/data/shared/LA_listeria/temp',
        '/data/shared/LA_refid/temp',
        '/data/shared/LA_salmonella/temp',
        '/data/shared/LAC_campy/temp',
        '/data/shared/LAC_escherichia/temp',
        '/data/shared/LAC_listeria/temp',
        '/data/shared/LAC_refid/temp',
        '/data/shared/LAC_salmonella/temp',
        '/data/shared/MA_campy/temp',
        '/data/shared/MA_escherichia/temp',
        '/data/shared/MA_listeria/temp',
        '/data/shared/MA_refid/temp',
        '/data/shared/MA_salmonella/temp',
        '/data/shared/MD_campy/temp',
        '/data/shared/MD_escherichia/temp',
        '/data/shared/MD_listeria/temp',
        '/data/shared/MD_refid/temp',
        '/data/shared/MD_salmonella/temp',
        '/data/shared/ME_campy/temp',
        '/data/shared/ME_escherichia/temp',
        '/data/shared/ME_listeria/temp',
        '/data/shared/ME_refid/temp',
        '/data/shared/ME_salmonella/temp',
        '/data/shared/MI_campy/temp',
        '/data/shared/MI_escherichia/temp',
        '/data/shared/MI_listeria/temp',
        '/data/shared/MI_refid/temp',
        '/data/shared/MI_salmonella/temp',
        '/data/shared/MN_campy/temp',
        '/data/shared/MN_escherichia/temp',
        '/data/shared/MN_listeria/temp',
        '/data/shared/MN_refid/temp',
        '/data/shared/MN_salmonella/temp',
        '/data/shared/MO_campy/temp',
        '/data/shared/MO_escherichia/temp',
        '/data/shared/MO_listeria/temp',
        '/data/shared/MO_refid/temp',
        '/data/shared/MO_salmonella/temp',
        '/data/shared/MS_campy/temp',
        '/data/shared/MS_escherichia/temp',
        '/data/shared/MS_listeria/temp',
        '/data/shared/MS_refid/temp',
        '/data/shared/MS_salmonella/temp',
        '/data/shared/MT_campy/temp',
        '/data/shared/MT_escherichia/temp',
        '/data/shared/MT_listeria/temp',
        '/data/shared/MT_refid/temp',
        '/data/shared/MT_salmonella/temp',
        '/data/shared/NC_campy/temp',
        '/data/shared/NC_escherichia/temp',
        '/data/shared/NC_listeria/temp',
        '/data/shared/NC_refid/temp',
        '/data/shared/NC_salmonella/temp',
        '/data/shared/ND_campy/temp',
        '/data/shared/ND_escherichia/temp',
        '/data/shared/ND_listeria/temp',
        '/data/shared/ND_refid/temp',
        '/data/shared/ND_salmonella/temp',
        '/data/shared/NE_campy/temp',
        '/data/shared/NE_escherichia/temp',
        '/data/shared/NE_listeria/temp',
        '/data/shared/NE_refid/temp',
        '/data/shared/NE_salmonella/temp',
        '/data/shared/NH_campy/temp',
        '/data/shared/NH_escherichia/temp',
        '/data/shared/NH_listeria/temp',
        '/data/shared/NH_refid/temp',
        '/data/shared/NH_salmonella/temp',
        '/data/shared/NM_campy/temp',
        '/data/shared/NM_escherichia/temp',
        '/data/shared/NM_listeria/temp',
        '/data/shared/NM_refid/temp',
        '/data/shared/NM_salmonella/temp',
        '/data/shared/NV_campy/temp',
        '/data/shared/NV_escherichia/temp',
        '/data/shared/NV_listeria/temp',
        '/data/shared/NV_refid/temp',
        '/data/shared/NV_salmonella/temp',
        '/data/shared/NY_campy/temp',
        '/data/shared/NY_escherichia/temp',
        '/data/shared/NY_listeria/temp',
        '/data/shared/NY_refid/temp',
        '/data/shared/NY_salmonella/temp',
        '/data/shared/NYC_campy/temp',
        '/data/shared/NYC_escherichia/temp',
        '/data/shared/NYC_listeria/temp',
        '/data/shared/NYC_refid/temp',
        '/data/shared/NYC_salmonella/temp',
        '/data/shared/OH_campy/temp',
        '/data/shared/OH_escherichia/temp',
        '/data/shared/OH_listeria/temp',
        '/data/shared/OH_refid/temp',
        '/data/shared/OH_salmonella/temp',
        '/data/shared/OK_campy/temp',
        '/data/shared/OK_escherichia/temp',
        '/data/shared/OK_listeria/temp',
        '/data/shared/OK_refid/temp',
        '/data/shared/OK_salmonella/temp',
        '/data/shared/OR_campy/temp',
        '/data/shared/OR_escherichia/temp',
        '/data/shared/OR_listeria/temp',
        '/data/shared/OR_refid/temp',
        '/data/shared/OR_salmonella/temp',
        '/data/shared/PA_campy/temp',
        '/data/shared/PA_escherichia/temp',
        '/data/shared/PA_listeria/temp',
        '/data/shared/PA_refid/temp',
        '/data/shared/PA_salmonella/temp',
        '/data/shared/RI_campy/temp',
        '/data/shared/RI_escherichia/temp',
        '/data/shared/RI_listeria/temp',
        '/data/shared/RI_refid/temp',
        '/data/shared/RI_salmonella/temp',
        '/data/shared/SC_campy/temp',
        '/data/shared/SC_escherichia/temp',
        '/data/shared/SC_listeria/temp',
        '/data/shared/SC_refid/temp',
        '/data/shared/SC_salmonella/temp',
        '/data/shared/SD_campy/temp',
        '/data/shared/SD_escherichia/temp',
        '/data/shared/SD_listeria/temp',
        '/data/shared/SD_refid/temp',
        '/data/shared/SD_salmonella/temp',
        '/data/shared/SDC_campy/temp',
        '/data/shared/SDC_escherichia/temp',
        '/data/shared/SDC_listeria/temp',
        '/data/shared/SDC_refid/temp',
        '/data/shared/SDC_salmonella/temp',
        '/data/shared/TN_campy/temp',
        '/data/shared/TN_escherichia/temp',
        '/data/shared/TN_listeria/temp',
        '/data/shared/TN_refid/temp',
        '/data/shared/TN_salmonella/temp',
        '/data/shared/TX_campy/temp',
        '/data/shared/TX_escherichia/temp',
        '/data/shared/TX_listeria/temp',
        '/data/shared/TX_refid/temp',
        '/data/shared/TX_salmonella/temp',
        '/data/shared/USDA_campy/temp',
        '/data/shared/USDA_escherichia/temp',
        '/data/shared/USDA_listeria/temp',
        '/data/shared/USDA_refid/temp',
        '/data/shared/USDA_salmonella/temp',
        '/data/shared/UT_campy/temp',
        '/data/shared/UT_escherichia/temp',
        '/data/shared/UT_listeria/temp',
        '/data/shared/UT_refid/temp',
        '/data/shared/UT_salmonella/temp',
        '/data/shared/VA_campy/temp',
        '/data/shared/VA_escherichia/temp',
        '/data/shared/VA_listeria/temp',
        '/data/shared/VA_refid/temp',
        '/data/shared/VA_salmonella/temp',
        '/data/shared/VT_campy/temp',
        '/data/shared/VT_escherichia/temp',
        '/data/shared/VT_listeria/temp',
        '/data/shared/VT_refid/temp',
        '/data/shared/VT_salmonella/temp',
        '/data/shared/WA_campy/temp',
        '/data/shared/WA_escherichia/temp',
        '/data/shared/WA_listeria/temp',
        '/data/shared/WA_refid/temp',
        '/data/shared/WA_salmonella/temp',
        '/data/shared/WI_campy/temp',
        '/data/shared/WI_escherichia/temp',
        '/data/shared/WI_listeria/temp',
        '/data/shared/WI_refid/temp',
        '/data/shared/WI_salmonella/temp',
        '/data/shared/WY_campy/temp',
        '/data/shared/WY_escherichia/temp',
        '/data/shared/WY_listeria/temp',
        '/data/shared/WY_refid/temp',
        '/data/shared/WY_salmonella/temp'
        ]

    for dir in temp_dirs:
        dir_id = dir.split('/')[3]
        if os.path.isdir(dir):
            # first list all dirs in temp dir 
            fd = [os.path.join(dir, f) for f in next(os.walk(dir))[1]]
            # second list all dirs to be removed
            rm_dirs = [d for d in fd if datetime.fromtimestamp(os.stat(dir).st_mtime) < cutoff_date]
            for dirpath in rm_dirs:
                try:
                    ## UNCOMMENT LINE BELOW TO ENABLE REMOVE CALL
                    # shutil.rmtree(dirpath)
                    print('#SUCCESS! -- {}/temp: removed {} / {} temp directories'.format(dir_id, len(rm_dirs), len(fd)))
                except Exception as e:
                    print('Error removing {}'.format(dirpath))
                    print('{}'.format(e))
        else:
            print('== {} does not exist, moving on'.format(dir_id))
            continue
